apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: docker-deploy-from-github
  title: Deploy Docker from GitHub Repo
  description: Create and deploy a Docker container from a GitHub repository URL.
spec:
  owner: user:guest
  type: service

  
  parameters:
    - title: GitHub Repository URL
      required: 
        - Github_URL
      properties:
        Github_URL:
          title: Enter you Github URL
          type: string
          description: Enter the github URL where your code exists
          ui:autofocus: true

    - title: Container Settings
      required:
        - Port
        - Dockerfile_Path
      properties:
        Port:
          title: Host Port
          type: string
          description: Enter the port number to expose (e.g., 8080)
        Dockerfile_Path:
          title: Path to Dockerfile
          type: string
          description: Relative path to Dockerfile (e.g., `Dockerfile` or `docker/Dockerfile`)
          default: "Dockerfile"   
          
# parameters:
#   - title: Fill in project details
#     required:
#       - name
#       - description
#       - owner
#     properties:
#       name:
#         title: Project Name
#         type: string
#         description: What’s the name of your project?
#         ui:autofocus: true
          
  steps:
    - id: fetch-template
      name: Fetch template files
      action: fetch:plain
      input:
        url: ${{ parameters.Github_URL }}
        targetPath: .
    #Previous code throug this template will appear but it will not execute
    # - id: build_docker
    #   name: Build Docker Image
    #   action: shell:run
    #   input:
    #     workingDirectory: ${{ steps.clone.output.path }}
    #     command: |
    #       docker build -t my-image:latest .

    - id: build_docker
      name: Build Docker Image
      action: shell:run
      input:
        cwd: ${{ steps.fetch-template.output.path }}
        command: docker 
        args: ["build", "-f", "${{ parameters.Dockerfile_Path }}", "--progress=plain", "--no-cache", "-t", "my-image:latest", "build/"]
        log: true


    - id: cleanup
      name: Remove old container if exists
      action: shell:run
      input:
        command: docker
        args: ["rm", "-f", "Cafe-container"]
                

    - id: deploy_docker
      name: Deploy Docker Container
      action: shell:run
      input:
        cwd: ${{ steps.fetch-template.output.path }}
        command: docker
        args: ["run", "--name", "Cafe-container", "-it", "-d", "-p", "89:${{ parameters.Port }}", "my-image:latest"]

    # - id: run-echo
    #   name: Echo Test
    #   action: shell:run
    #   input:
    #     command: echo
    #     args: ["Hello Backstage!"]
